---
name: 🐛 Bug report
about: Create a report to help us improve our product
title: '[BUG] <title>'
labels: 'bug'
assignees: ''

body:
- type: textarea
  attributes:
    label: How do you reproduce this bug?
    description: Explain in clear steps how you encounered the bug.
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Expected Behaviour
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Screenshots
    description: If applicable, add screenshots to help explain your problem.
  validations:
    required: false

- type: textarea
  attributes:
    label: Website Environment
    description: |
     - PHP Version: [e.g. 7.4]
     - Database driver (please include the version aswell): [e.g. MySQL 5.8, MariaDB 10.6]
     - Application Version: [e.g. 1.2.5]
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Additional Information
    description: Any other information regarding the issue
  validations:
    required: false
