
name: 🐛 Bug report
description: Create a report to help us improve our product
labels: 'bug'


body:

- type: textarea
  attributes:
    label: Description of the bug
    description: Clearly and concisely describe the bug you have found.
    placeholder: The bug I have found is...
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Error
    description: Present the error code for the web application, or any errors relating to an integration. (e.g Garry's Mod)
    placeholder: I got this error...
  validations:
    required: false
    
- type: textarea
  attributes:
    label: How do you reproduce this bug?
    description: Explain in clear steps how you encounered the bug.
    placeholder: To reproduce the bug...
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Expected Behaviour
    description: A clear and concise description of what you expected to happen.
    placeholder: I expected Cosmo to...
  validations:
    required: true

- type: textarea
  attributes:
    label: Website Environment
    description: Specifics about Cosmo's Environment
    value: |
     - PHP Version: [e.g. 7.4]
     - Database driver (please include the version aswell): [e.g. MySQL 5.8, MariaDB 10.6]
     - Application Version: [e.g. 1.2.5]
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Additional Information
    description: Any other information, screenshots or regarding the issue.
    placeholder: Here are some screenshots...
  validations:
    required: false
