
name: 🌟 Feature request
description: Suggest a feature for the product
title: '[FEAT] <title>'
labels: 'feature'


body:
- type: textarea
  attributes:
    label: Description of the feature
    description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Examples of the feature
    description: A clear and concise description of the feature, and screenshots if applicable.
  validations:
    required: true

- type: textarea
  attributes:
    label: Alternatives for the feature
    description: List and explain any alternatives for the feature or other features you have considerd.
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Additional Context
    description: Any other info, context or screenshots about the feature.
  validations:
    required: true
