
name: 🌟 Feature request
description: Suggest a feature for Cosmo.
labels: 'feature'


body:
- type: textarea
  attributes:
    label: Description of the feature
    description: A clear and concise description of what the problem is.
    placeholder: I would like to see...
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Examples of the feature
    description: A clear and concise description of the feature, and screenshots if applicable.
  validations:
    required: true

- type: textarea
  attributes:
    label: Alternatives for the feature
    description: Any alternative options for this feature, or products that do this
  validations:
    required: false
    
- type: textarea
  attributes:
    label: Additional Context
    description: Any other info, context or screenshots about the feature.
  validations:
    required: false
